# Generated by Django 5.2.7 on 2025-12-03 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PulleyDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_image", models.ImageField(upload_to="uploads/")),
                ("result_image", models.ImageField(upload_to="results/")),
                ("temperature_c", models.FloatField(blank=True, null=True)),
                ("htl_value", models.FloatField(blank=True, null=True)),
                ("dist_p1_p2", models.FloatField(blank=True, null=True)),
                ("dist_p2_p3", models.FloatField(blank=True, null=True)),
                ("total_distance", models.FloatField(blank=True, null=True)),
                ("expected_total", models.FloatField(blank=True, null=True)),
                ("loss_mm", models.FloatField(blank=True, null=True)),
                ("distances", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "dist12",
                    models.FloatField(
                        blank=True,
                        help_text="Distance between pulley 1 and 2 (mm)",
                        null=True,
                    ),
                ),
                (
                    "dist23",
                    models.FloatField(
                        blank=True,
                        help_text="Distance between pulley 2 and 3 (mm)",
                        null=True,
                    ),
                ),
                (
                    "total",
                    models.FloatField(
                        blank=True, help_text="Total distance P1->P3 (mm)", null=True
                    ),
                ),
                (
                    "expected_total",
                    models.FloatField(
                        blank=True, help_text="Expected total distance (mm)", null=True
                    ),
                ),
                (
                    "expected_dist12",
                    models.FloatField(
                        blank=True, help_text="Expected distance P1->P2 (mm)", null=True
                    ),
                ),
                (
                    "expected_dist23",
                    models.FloatField(
                        blank=True, help_text="Expected distance P2->P3 (mm)", null=True
                    ),
                ),
                (
                    "loss_mm",
                    models.FloatField(
                        blank=True, help_text="Loss vs expected (mm)", null=True
                    ),
                ),
                (
                    "pulley_count",
                    models.IntegerField(
                        default=0, help_text="Number of pulleys detected"
                    ),
                ),
                (
                    "temperature_c",
                    models.FloatField(
                        blank=True, help_text="Temperature in Celsius", null=True
                    ),
                ),
                (
                    "points_json",
                    models.TextField(
                        blank=True, help_text="Pulley center points", null=True
                    ),
                ),
                (
                    "image_path",
                    models.ImageField(
                        blank=True,
                        help_text="Saved annotated image file",
                        null=True,
                        upload_to="best_captures/",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="pulley_app__timesta_7605a6_idx"
                    )
                ],
            },
        ),
    ]
