# Generated by Django 5.2.7 on 2025-12-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pulley_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detectionrecord",
            name="user",
        ),
    ]
