# Generated by Django 5.2.7 on 2025-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulley_app', '0003_add_user_and_htl_to_detectionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrecord',
            name='pole_name',
            field=models.CharField(blank=True, help_text='Name/identifier of the pole', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pulleydetection',
            name='pole_name',
            field=models.CharField(blank=True, help_text='Name/identifier of the pole', max_length=255, null=True),
        ),
    ]
