# Generated by Django 5.2.9 on 2026-01-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulley_app", "0004_detectionrecord_pole_name_pulleydetection_pole_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulleydetection",
            name="regulating_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pulleydetection",
            name="station",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
