# Generated by Django 5.2.9 on 2026-01-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulley_app", "0005_pulleydetection_regulating_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulleydetection",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pulleydetection",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
