# Generated by Django 5.2.9 on 2026-01-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pulley_app", "0006_pulleydetection_latitude_pulleydetection_longitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pulleydetection",
            old_name="longitude",
            new_name="longtitude",
        ),
    ]
