# Generated by Django 5.2.9 on 2026-01-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pulley_app", "0007_rename_longitude_pulleydetection_longtitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pulleydetection",
            old_name="longtitude",
            new_name="Longitude",
        ),
    ]
