# Generated by Django 5.2.9 on 2026-01-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pulley_app", "0008_rename_longtitude_pulleydetection_longitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pulleydetection",
            old_name="Longitude",
            new_name="longitude",
        ),
    ]
